# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .one_service_api_documentation import OneServiceAPIDocumentation
from .version import VERSION

__all__ = ['OneServiceAPIDocumentation']

__version__ = VERSION

