# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from .msn_tags_data_model_tag_entity_lib_metadata import MsnTagsDataModelTagEntityLibMetadata
from .msn_tags_data_model_tag_entity_lib_composite_card import MsnTagsDataModelTagEntityLibCompositeCard
from .msn_one_web_service_swagger_odata_response_msn_tags_data_model_tag_entity_lib_composite_card import MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibCompositeCard
from .msn_tags_data_model_tag_entity_lib_actionable import MsnTagsDataModelTagEntityLibActionable
from .msn_one_web_service_swagger_odata_error_item import MsnOneWebServiceSwaggerODataErrorItem
from .msn_one_web_service_swagger_odata_error_response import MsnOneWebServiceSwaggerODataErrorResponse
from .msn_tags_data_model_tag_entity_lib_artifact_data_tag import MsnTagsDataModelTagEntityLibArtifactDataTag
from .msn_tags_data_model_tag_entity_lib_artifact_data_close_caption import MsnTagsDataModelTagEntityLibArtifactDataCloseCaption
from .msn_tags_data_model_tag_entity_lib_artifact_data_external_video_file import MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile
from .msn_tags_data_model_tag_entity_lib_artifact_data_video_metadata import MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata
from .msn_tags_data_model_tag_entity_lib_artifact_data_focal_region import MsnTagsDataModelTagEntityLibArtifactDataFocalRegion
from .msn_tags_data_model_tag_entity_lib_artifact_data_image import MsnTagsDataModelTagEntityLibArtifactDataImage
from .microsoft_news_api_contracts_provider_summary_view import MicrosoftNewsApiContractsProviderSummaryView
from .microsoft_news_api_contracts_source_feed_view import MicrosoftNewsApiContractsSourceFeedView
from .microsoft_news_api_contracts_feed_item_view_v1 import MicrosoftNewsApiContractsFeedItemViewV1
from .msn_one_web_service_swagger_odata_response_microsoft_news_api_contracts_feed_item_view_v1 import MsnOneWebServiceSwaggerODataResponseMicrosoftNewsApiContractsFeedItemViewV1
from .msn_tags_data_model_tag_entity_lib_market import MsnTagsDataModelTagEntityLibMarket
from .msn_one_web_service_swagger_odata_response_msn_tags_data_model_tag_entity_lib_market import MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibMarket
from .msn_tags_data_model_tag_entity_lib_artifact_data_provider_summary import MsnTagsDataModelTagEntityLibArtifactDataProviderSummary
from .msn_tags_data_model_tag_entity_lib_artifact_data_headline import MsnTagsDataModelTagEntityLibArtifactDataHeadline
from .msn_tags_data_model_tag_entity_lib_artifact_data_tag_evaluation_group import MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup
from .msn_tags_data_model_tag_entity_lib_artifact_data_category import MsnTagsDataModelTagEntityLibArtifactDataCategory
from .msn_tags_data_model_tag_entity_lib_artifact import MsnTagsDataModelTagEntityLibArtifact
from .msn_tags_data_model_tag_entity_lib_artifact_data_parent import MsnTagsDataModelTagEntityLibArtifactDataParent
from .msn_tags_data_model_tag_entity_lib_location import MsnTagsDataModelTagEntityLibLocation
from .msn_tags_data_model_tag_entity_lib_sys_tag import MsnTagsDataModelTagEntityLibSysTag

__all__ = [
    'MsnTagsDataModelTagEntityLibMetadata',
    'MsnTagsDataModelTagEntityLibCompositeCard',
    'MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibCompositeCard',
    'MsnTagsDataModelTagEntityLibActionable',
    'MsnOneWebServiceSwaggerODataErrorItem',
    'MsnOneWebServiceSwaggerODataErrorResponse',
    'MsnTagsDataModelTagEntityLibArtifactDataTag',
    'MsnTagsDataModelTagEntityLibArtifactDataCloseCaption',
    'MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile',
    'MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata',
    'MsnTagsDataModelTagEntityLibArtifactDataFocalRegion',
    'MsnTagsDataModelTagEntityLibArtifactDataImage',
    'MicrosoftNewsApiContractsProviderSummaryView',
    'MicrosoftNewsApiContractsSourceFeedView',
    'MicrosoftNewsApiContractsFeedItemViewV1',
    'MsnOneWebServiceSwaggerODataResponseMicrosoftNewsApiContractsFeedItemViewV1',
    'MsnTagsDataModelTagEntityLibMarket',
    'MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibMarket',
    'MsnTagsDataModelTagEntityLibArtifactDataProviderSummary',
    'MsnTagsDataModelTagEntityLibArtifactDataHeadline',
    'MsnTagsDataModelTagEntityLibArtifactDataTagEvaluationGroup',
    'MsnTagsDataModelTagEntityLibArtifactDataCategory',
    'MsnTagsDataModelTagEntityLibArtifact',
    'MsnTagsDataModelTagEntityLibArtifactDataParent',
    'MsnTagsDataModelTagEntityLibLocation',
    'MsnTagsDataModelTagEntityLibSysTag',
]
