# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftNewsApiContractsSourceFeedView(Model):
    """MicrosoftNewsApiContractsSourceFeedView.

    :param id: The unique identifier for the Feed
    :type id: str
    :param feed_name: The name of the feed
    :type feed_name: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'feed_name': {'key': 'feedName', 'type': 'str'},
    }

    def __init__(self, id=None, feed_name=None):
        super(MicrosoftNewsApiContractsSourceFeedView, self).__init__()
        self.id = id
        self.feed_name = feed_name
