# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftNewsApiContractsFeedItemViewV1(Model):
    """MicrosoftNewsApiContractsFeedItemViewV1.

    :param id: The unique identifier for this Feed Item
    :type id: str
    :param type: The feed item type. This may be an article, video, or
     slideshow
    :type type: str
    :param next_page_url: This provides the Next Page URL for calls that need
     pagination.
    :type next_page_url: str
    :param title: The item title
    :type title: str
    :param sub_title: The item subtitle
    :type sub_title: str
    :param abstract: The item abstract
    :type abstract: str
    :param url: The URL to the content view page
    :type url: str
    :param data_url: The Data URL. This is provided for feed items that have
     data sources in addition to their view URL
    :type data_url: str
    :param locale: The Locale that the content is presented in
    :type locale: str
    :param topics: The list of Topics that this content is associated with
     along with the Feed name and ID for each.
    :type topics:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataTag]
    :param gallery_item_count: The number of items in the slideshow gallery.
     This property is only defined for Slideshow feed items.
    :type gallery_item_count: int
    :param video_metadata:
    :type video_metadata:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata
    :param external_video_files: The list of extenal video files. This
     property is defined for Video feed items.
    :type external_video_files:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile]
    :param images: The list of Images available for the feed item headline
    :type images:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataImage]
    :param provider:
    :type provider:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MicrosoftNewsApiContractsProviderSummaryView
    :param category: The primary category that this content is classified into
    :type category: str
    :param published_date_time: The date and time when the content was
     published by the source provider.
    :type published_date_time: str
    :param feed:
    :type feed:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MicrosoftNewsApiContractsSourceFeedView
    :param sub_cards: The collection of nested items related to this Feed
     Item.
    :type sub_cards:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MicrosoftNewsApiContractsFeedItemViewV1]
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'next_page_url': {'key': 'nextPageUrl', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'sub_title': {'key': 'subTitle', 'type': 'str'},
        'abstract': {'key': 'abstract', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
        'data_url': {'key': 'dataUrl', 'type': 'str'},
        'locale': {'key': 'locale', 'type': 'str'},
        'topics': {'key': 'topics', 'type': '[MsnTagsDataModelTagEntityLibArtifactDataTag]'},
        'gallery_item_count': {'key': 'galleryItemCount', 'type': 'int'},
        'video_metadata': {'key': 'videoMetadata', 'type': 'MsnTagsDataModelTagEntityLibArtifactDataVideoMetadata'},
        'external_video_files': {'key': 'externalVideoFiles', 'type': '[MsnTagsDataModelTagEntityLibArtifactDataExternalVideoFile]'},
        'images': {'key': 'images', 'type': '[MsnTagsDataModelTagEntityLibArtifactDataImage]'},
        'provider': {'key': 'provider', 'type': 'MicrosoftNewsApiContractsProviderSummaryView'},
        'category': {'key': 'category', 'type': 'str'},
        'published_date_time': {'key': 'publishedDateTime', 'type': 'str'},
        'feed': {'key': 'feed', 'type': 'MicrosoftNewsApiContractsSourceFeedView'},
        'sub_cards': {'key': 'subCards', 'type': '[MicrosoftNewsApiContractsFeedItemViewV1]'},
    }

    def __init__(self, id=None, type=None, next_page_url=None, title=None, sub_title=None, abstract=None, url=None, data_url=None, locale=None, topics=None, gallery_item_count=None, video_metadata=None, external_video_files=None, images=None, provider=None, category=None, published_date_time=None, feed=None, sub_cards=None):
        super(MicrosoftNewsApiContractsFeedItemViewV1, self).__init__()
        self.id = id
        self.type = type
        self.next_page_url = next_page_url
        self.title = title
        self.sub_title = sub_title
        self.abstract = abstract
        self.url = url
        self.data_url = data_url
        self.locale = locale
        self.topics = topics
        self.gallery_item_count = gallery_item_count
        self.video_metadata = video_metadata
        self.external_video_files = external_video_files
        self.images = images
        self.provider = provider
        self.category = category
        self.published_date_time = published_date_time
        self.feed = feed
        self.sub_cards = sub_cards
