# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MicrosoftNewsApiContractsProviderSummaryView(Model):
    """MicrosoftNewsApiContractsProviderSummaryView.

    :param id: The unique identifier of the Content Provider in the Microsoft
     News graph.
    :type id: str
    :param name: The display name for the provider
    :type name: str
    :param logo_url: The URL of the provider logo
    :type logo_url: str
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'logo_url': {'key': 'logoUrl', 'type': 'str'},
    }

    def __init__(self, id=None, name=None, logo_url=None):
        super(MicrosoftNewsApiContractsProviderSummaryView, self).__init__()
        self.id = id
        self.name = name
        self.logo_url = logo_url
