# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataHeadline(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataHeadline.

    :param title: Gets or sets Title
    :type title: str
    :param sub_title: Gets or sets the sub title.
    :type sub_title: str
    :param kicker: Gets or sets the kicker.
    :type kicker: str
    :param image_caption: Gets or sets ImageCaption
    :type image_caption: str
    :param image:
    :type image:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataImage
    :param created_by: Gets or sets CreatedBy
    :type created_by: str
    """

    _attribute_map = {
        'title': {'key': 'title', 'type': 'str'},
        'sub_title': {'key': 'subTitle', 'type': 'str'},
        'kicker': {'key': 'kicker', 'type': 'str'},
        'image_caption': {'key': 'imageCaption', 'type': 'str'},
        'image': {'key': 'image', 'type': 'MsnTagsDataModelTagEntityLibArtifactDataImage'},
        'created_by': {'key': 'createdBy', 'type': 'str'},
    }

    def __init__(self, title=None, sub_title=None, kicker=None, image_caption=None, image=None, created_by=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataHeadline, self).__init__()
        self.title = title
        self.sub_title = sub_title
        self.kicker = kicker
        self.image_caption = image_caption
        self.image = image
        self.created_by = created_by
