# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataCloseCaption(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataCloseCaption.

    :param locale: Gets or sets the locale.
    :type locale: str
    :param href: Gets or sets the HREF.
    :type href: str
    """

    _attribute_map = {
        'locale': {'key': 'locale', 'type': 'str'},
        'href': {'key': 'href', 'type': 'str'},
    }

    def __init__(self, locale=None, href=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataCloseCaption, self).__init__()
        self.locale = locale
        self.href = href
