# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataImage(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataImage.

    :param width: Gets or sets Width
    :type width: int
    :param height: Gets or sets Height
    :type height: int
    :param quality: Gets or sets Quality
    :type quality: int
    :param url: Gets or sets Url
    :type url: str
    :param attribution: Gets or sets Attribution
    :type attribution: str
    :param title: Gets or sets Title
    :type title: str
    :param focal_region:
    :type focal_region:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataFocalRegion
    :param source: Gets or sets the source.
    :type source: str
    """

    _attribute_map = {
        'width': {'key': 'width', 'type': 'int'},
        'height': {'key': 'height', 'type': 'int'},
        'quality': {'key': 'quality', 'type': 'int'},
        'url': {'key': 'url', 'type': 'str'},
        'attribution': {'key': 'attribution', 'type': 'str'},
        'title': {'key': 'title', 'type': 'str'},
        'focal_region': {'key': 'focalRegion', 'type': 'MsnTagsDataModelTagEntityLibArtifactDataFocalRegion'},
        'source': {'key': 'source', 'type': 'str'},
    }

    def __init__(self, width=None, height=None, quality=None, url=None, attribution=None, title=None, focal_region=None, source=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataImage, self).__init__()
        self.width = width
        self.height = height
        self.quality = quality
        self.url = url
        self.attribution = attribution
        self.title = title
        self.focal_region = focal_region
        self.source = source
