# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibActionable(Model):
    """MsnTagsDataModelTagEntityLibActionable.

    :param title: Get or set the EntityName of the Actionable
    :type title: str
    :param type: Get or set the Type of the Card.
     Please use ContentTypes for this property although we don't use a strong
     name for easier backward compatibilty for future extension.
    :type type: str
    :param url: Get or set the Clickable Url of the Card
    :type url: str
    :param data_url: Get or set the Fetchable Data Url of the Card Content
    :type data_url: str
    :param locale: Gets or sets Locale of the Card (optional) for extra
     information purpose.
    :type locale: str
    :param _p: Get or set the PartitionKey of the entity
    :type _p: str
    :param created_by: Get or set the CreatedBy of the entity
    :type created_by: str
    :param created_date_time: Get or set the CreateDate of the entity
    :type created_date_time: str
    :param updated_date_time: Get or set the ModifiedDate of the entity
    :type updated_date_time: str
    :param deleted: Get or set whether the entity is Deleted
    :type deleted: bool
    :param _et: Get or set the extended type
    :type _et: str
    :param id:
    :type id: str
    :param _t:
    :type _t: str
    :param _etag:
    :type _etag: str
    :param _rid:
    :type _rid: str
    :param _self:
    :type _self: str
    :param _ts:
    :type _ts: long
    :param ttl:
    :type ttl: int
    :param is_dirty:
    :type is_dirty: bool
    :param has_error:
    :type has_error: bool
    :param item:
    :type item: object
    :param property_bag:
    :type property_bag: list[object]
    """

    _attribute_map = {
        'title': {'key': 'title', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
        'url': {'key': 'url', 'type': 'str'},
        'data_url': {'key': 'dataUrl', 'type': 'str'},
        'locale': {'key': 'locale', 'type': 'str'},
        '_p': {'key': '_p', 'type': 'str'},
        'created_by': {'key': 'createdBy', 'type': 'str'},
        'created_date_time': {'key': 'createdDateTime', 'type': 'str'},
        'updated_date_time': {'key': 'updatedDateTime', 'type': 'str'},
        'deleted': {'key': 'deleted', 'type': 'bool'},
        '_et': {'key': '_et', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        '_t': {'key': '_t', 'type': 'str'},
        '_etag': {'key': '_etag', 'type': 'str'},
        '_rid': {'key': '_rid', 'type': 'str'},
        '_self': {'key': '_self', 'type': 'str'},
        '_ts': {'key': '_ts', 'type': 'long'},
        'ttl': {'key': 'ttl', 'type': 'int'},
        'is_dirty': {'key': 'isDirty', 'type': 'bool'},
        'has_error': {'key': 'hasError', 'type': 'bool'},
        'item': {'key': 'item', 'type': 'object'},
        'property_bag': {'key': 'propertyBag', 'type': '[object]'},
    }

    def __init__(self, title=None, type=None, url=None, data_url=None, locale=None, _p=None, created_by=None, created_date_time=None, updated_date_time=None, deleted=None, _et=None, id=None, _t=None, _etag=None, _rid=None, _self=None, _ts=None, ttl=None, is_dirty=None, has_error=None, item=None, property_bag=None):
        super(MsnTagsDataModelTagEntityLibActionable, self).__init__()
        self.title = title
        self.type = type
        self.url = url
        self.data_url = data_url
        self.locale = locale
        self._p = _p
        self.created_by = created_by
        self.created_date_time = created_date_time
        self.updated_date_time = updated_date_time
        self.deleted = deleted
        self._et = _et
        self.id = id
        self._t = _t
        self._etag = _etag
        self._rid = _rid
        self._self = _self
        self._ts = _ts
        self.ttl = ttl
        self.is_dirty = is_dirty
        self.has_error = has_error
        self.item = item
        self.property_bag = property_bag
