# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataProviderSummary(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataProviderSummary.

    :param id: Gets or sets Id
    :type id: str
    :param name: Gets or sets Name
    :type name: str
    :param ad_network_id: Gets or sets AdNetworkId
    :type ad_network_id: str
    :param logo:
    :type logo:
     ~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibArtifactDataImage
    """

    _attribute_map = {
        'id': {'key': 'id', 'type': 'str'},
        'name': {'key': 'name', 'type': 'str'},
        'ad_network_id': {'key': 'adNetworkId', 'type': 'str'},
        'logo': {'key': 'logo', 'type': 'MsnTagsDataModelTagEntityLibArtifactDataImage'},
    }

    def __init__(self, id=None, name=None, ad_network_id=None, logo=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataProviderSummary, self).__init__()
        self.id = id
        self.name = name
        self.ad_network_id = ad_network_id
        self.logo = logo
