# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibLocation(Model):
    """MsnTagsDataModelTagEntityLibLocation.

    :param country_code: Gets or sets the two characters country ISO code like
     US, CA.
    :type country_code: str
    :param subdivision: Gets or sets the subdivision.
    :type subdivision: str
    :param city: Gets or sets the city.
    :type city: str
    :param latitude: Gets or sets the latitude.
    :type latitude: float
    :param longitude: Gets or sets the longitude.
    :type longitude: float
    """

    _attribute_map = {
        'country_code': {'key': 'countryCode', 'type': 'str'},
        'subdivision': {'key': 'subdivision', 'type': 'str'},
        'city': {'key': 'city', 'type': 'str'},
        'latitude': {'key': 'latitude', 'type': 'float'},
        'longitude': {'key': 'longitude', 'type': 'float'},
    }

    def __init__(self, country_code=None, subdivision=None, city=None, latitude=None, longitude=None):
        super(MsnTagsDataModelTagEntityLibLocation, self).__init__()
        self.country_code = country_code
        self.subdivision = subdivision
        self.city = city
        self.latitude = latitude
        self.longitude = longitude
