# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataFocalRegion(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataFocalRegion.

    :param x1: Gets or sets X1
    :type x1: int
    :param x2: Gets or sets X2
    :type x2: int
    :param y1: Gets or sets Y1
    :type y1: int
    :param y2: Gets or sets Y2
    :type y2: int
    """

    _attribute_map = {
        'x1': {'key': 'x1', 'type': 'int'},
        'x2': {'key': 'x2', 'type': 'int'},
        'y1': {'key': 'y1', 'type': 'int'},
        'y2': {'key': 'y2', 'type': 'int'},
    }

    def __init__(self, x1=None, x2=None, y1=None, y2=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataFocalRegion, self).__init__()
        self.x1 = x1
        self.x2 = x2
        self.y1 = y1
        self.y2 = y2
