# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnOneWebServiceSwaggerODataErrorResponse(Model):
    """MsnOneWebServiceSwaggerODataErrorResponse.

    :param odatacontext: Gets or sets the OdataContext
     Defines the odataContext
    :type odatacontext: str
    :param value: Gets or sets the Value
     Defines the value
    :type value:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MsnOneWebServiceSwaggerODataErrorItem]
    """

    _attribute_map = {
        'odatacontext': {'key': '@odata\\.context', 'type': 'str'},
        'value': {'key': 'value', 'type': '[MsnOneWebServiceSwaggerODataErrorItem]'},
    }

    def __init__(self, odatacontext=None, value=None):
        super(MsnOneWebServiceSwaggerODataErrorResponse, self).__init__()
        self.odatacontext = odatacontext
        self.value = value
