# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnOneWebServiceSwaggerODataResponseMicrosoftNewsApiContractsFeedItemViewV1(Model):
    """MsnOneWebServiceSwaggerODataResponseMicrosoftNewsApiContractsFeedItemViewV1.

    :param odatacontext:
    :type odatacontext: str
    :param value:
    :type value:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MicrosoftNewsApiContractsFeedItemViewV1]
    """

    _attribute_map = {
        'odatacontext': {'key': '@odata\\.context', 'type': 'str'},
        'value': {'key': 'value', 'type': '[MicrosoftNewsApiContractsFeedItemViewV1]'},
    }

    def __init__(self, odatacontext=None, value=None):
        super(MsnOneWebServiceSwaggerODataResponseMicrosoftNewsApiContractsFeedItemViewV1, self).__init__()
        self.odatacontext = odatacontext
        self.value = value
