# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnOneWebServiceSwaggerODataErrorItem(Model):
    """MsnOneWebServiceSwaggerODataErrorItem.

    :param error_message: Gets or sets the ErrorMessage
     Defines the errorMessage
    :type error_message: str
    """

    _attribute_map = {
        'error_message': {'key': 'errorMessage', 'type': 'str'},
    }

    def __init__(self, error_message=None):
        super(MsnOneWebServiceSwaggerODataErrorItem, self).__init__()
        self.error_message = error_message
