# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibMetadata(Model):
    """MsnTagsDataModelTagEntityLibMetadata.

    :param source: Gets or sets the source of the metadata.
    :type source: str
    """

    _attribute_map = {
        'source': {'key': 'source', 'type': 'str'},
    }

    def __init__(self, source=None):
        super(MsnTagsDataModelTagEntityLibMetadata, self).__init__()
        self.source = source
