# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataParent(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataParent.

    :param name: Gets or sets Name
    :type name: str
    :param id: Gets or sets Id
    :type id: str
    :param type: Gets or sets Type
    :type type: str
    """

    _attribute_map = {
        'name': {'key': 'name', 'type': 'str'},
        'id': {'key': 'id', 'type': 'str'},
        'type': {'key': 'type', 'type': 'str'},
    }

    def __init__(self, name=None, id=None, type=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataParent, self).__init__()
        self.name = name
        self.id = id
        self.type = type
