# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibMarket(Model):
    """MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibMarket.

    :param odatacontext:
    :type odatacontext: str
    :param value:
    :type value:
     list[~microsoft.swagger.codegen.microsoftnewsapi.models.MsnTagsDataModelTagEntityLibMarket]
    """

    _attribute_map = {
        'odatacontext': {'key': '@odata\\.context', 'type': 'str'},
        'value': {'key': 'value', 'type': '[MsnTagsDataModelTagEntityLibMarket]'},
    }

    def __init__(self, odatacontext=None, value=None):
        super(MsnOneWebServiceSwaggerODataResponseMsnTagsDataModelTagEntityLibMarket, self).__init__()
        self.odatacontext = odatacontext
        self.value = value
