# coding=utf-8
# --------------------------------------------------------------------------
# Code generated by Microsoft (R) AutoRest Code Generator.
# Changes may cause incorrect behavior and will be lost if the code is
# regenerated.
# --------------------------------------------------------------------------

from msrest.serialization import Model


class MsnTagsDataModelTagEntityLibArtifactDataCategory(Model):
    """MsnTagsDataModelTagEntityLibArtifactDataCategory.

    :param product: Gets or sets Product
    :type product: str
    :param label: Gets or sets Label
    :type label: str
    :param source: Gets or sets Source
    :type source: str
    :param score: Gets or sets Score
    :type score: float
    :param display_text: Gets or sets DisplayText
    :type display_text: str
    :param url_segment: Gets or sets UrlSegment
    :type url_segment: str
    """

    _attribute_map = {
        'product': {'key': 'product', 'type': 'str'},
        'label': {'key': 'label', 'type': 'str'},
        'source': {'key': 'source', 'type': 'str'},
        'score': {'key': 'score', 'type': 'float'},
        'display_text': {'key': 'displayText', 'type': 'str'},
        'url_segment': {'key': 'urlSegment', 'type': 'str'},
    }

    def __init__(self, product=None, label=None, source=None, score=None, display_text=None, url_segment=None):
        super(MsnTagsDataModelTagEntityLibArtifactDataCategory, self).__init__()
        self.product = product
        self.label = label
        self.source = source
        self.score = score
        self.display_text = display_text
        self.url_segment = url_segment
